project:
  type: website
  output-dir: docs
  resources:
    - "*.html"
  render:
    - "*.qmd"

execute:
  freeze: auto
  
website:
  title: "Lucas da Cunha Godoy"
  search: true
  cookie-consent: false
  twitter-card: false
  open-graph: true
  site-url: https://lcgodoy.me
  repo-url: https://github.com/lcgodoy/lcgodoy.github.io
  repo-actions: [issue]
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - publications.qmd
      - blog.qmd
      - talks.qmd
      - text: "CV"
        href: cv.pdf
    right:
      - icon: github
        href: https://github.com/lcgodoy
  page-footer: 
    left: "Copyright 2025, Lucas da Cunha Godoy"
        
format:
  html:
    theme:
      - customizing.scss
    mainfont: Noto Sans Mono # DM Mono
    toc: true
