---
title: |
  FROM POINT TO POLYGON: A UNIFIED FRAMEWORK FOR MODELING SPATIAL DEPENDENCE
description: |
    Talk given at the 2024 JSM
author: 
  - name: Lucas da Cunha Godoy
date: "2024-08-04"
categories:
  - Spatial statistics
  - Gaussian process
---

### Details

* **Date**: Aug 4, 2024

* **Location**: Portlant, OR

* [Slides](https://lcgodoy.me/slides/2024-jsm)

### Abstract

Accurate modeling of spatial dependence is pivotal in analyzing spatial data,
influencing parameter estimation and out-of-sample predictions. The spatial
structure and geometry of the data significantly impact valid statistical
inference. Existing models for areal data often rely on adjacency matrices,
struggling to differentiate between polygons of varying sizes and
shapes. Conversely, data fusion models, while effective, rely on computationally
intensive numerical integrals, presenting challenges for moderately large
datasets. In response to these issues, we propose the Hausdorff-Gaussian process
(HGP), a versatile model class utilizing the Hausdorff distance to capture
spatial dependence in both point and areal data. We introduce a valid
correlation function within the HGP framework, accommodating diverse modeling
techniques, including geostatistical and areal models. Integration into
generalized linear mixed-effects models enhances its applicability, particularly
in addressing change of support and data fusion challenges. We validate our
approach through a comprehensive simulation study and application to two
real-world scenarios: one involving areal data and another demonstrating its
effectiveness in data fusion. The results suggest that the HGP is competitive
with specialized models regarding goodness-of-fit and prediction
performances. In summary, the HGP offers a flexible and robust solution for
modeling spatial data of various types and shapes, with potential applications
spanning fields such as public health and climate science.


### Slides

```{=html}
<iframe width="100%" height="500" src="https://lcgodoy.me/slides/2024-jsm" title="Slides"></iframe>
```
