---
title: All models are wrong
author: Lucas Godoy
date: '2021-08-15'
slug: models
categories:
  - Statistics
tags: []
subtitle: ''
summary: |
  Comments on the famous George Box's quote and some highlights from the
  original text.
lastmod: '`r Sys.Date()`'
---

George Box's 1976 paper named ["Science and Statistics"](https://bit.ly/3rTAzlf)
is famous for that "all models are wrong" quote. Unfortunately, The number of
people who know this quote is larger than those who have read the paper
entirely.


The paper provides interesting (and insightful) discussions that still apply to
the field of statistics nowadays. In my opinion, one of the most remarkable
things Dr. Box pointed out is about "Mathematistry," he defines (or explains) it
as follows:
> "Mathematistry is characterized by development of theory for theory's sake,
> which since it seldom touches down with practice, has a tendency to redefine
> the problem rather than solve it."

Later on, in the same paper, he mentions how this "malady" (in his words) is
harmful to statistics as a field.
> "An even more serious consequence of mathematistry concerns the training of
> statisticians.  We have recently been passing through a period where nothing
> very much was expected of the statistician.  A great deal of research money
> was available and one had the curious situation where the highest objective of
> the teacher of statistics was to produce a student who would be another
> teacher of statistics.  It was thus possible for successive generations of
> teachers to be produced with no practical knowledge of the subject whatever.
> Although statistics departments in universities are now commonplace there
> continues to be a severe shortage of statisticians competent to deal with real
> problems. But such are needed."

We still face these challenges (on many others he mentioned in that paper) in
Statistics. Therefore, it would be nice to share this to make people think about
it.
