on:
  push:
     branches:
       - master

name: build_and_goto_gh_pages

jobs:
  blogdown:
    name: build_and_push_to_gh_pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown and blogdown
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown"))'
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo(extended = TRUE, version = "0.68.3")'
      - name: Get themes
        run: git submodule update --remote
      - name: Look at files
        run: Rscript -e 'dir()'
      - name: Run hugo_build()
        run: Rscript -e 'blogdown::hugo_build(local = FALSE)'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

# name: deployblog

# jobs:
#   blogdown:
#     name: Render-Blog
#     runs-on: macOS-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: r-lib/actions/setup-r@v1
#       - uses: r-lib/actions/setup-pandoc@v1
#       - name: Install rmarkdown
#         run: Rscript -e 'install.packages(c("rmarkdown","blogdown"))'
#       - name: install hugo
#         run: Rscript -e 'blogdown::install_hugo()'
#       - name: Render blog
#         run: Rscript -e 'blogdown::build_site()'
#       - uses: actions/upload-artifact@v1
#         with:
#           name: _site
#           path: _site/

# # Need to first create an empty gh-pages branch
# # see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# # and also add secrets for a GH_PAT and EMAIL to the repository
# # gh-action from Cecilapp/GitHub-Pages-deploy
#   checkout-and-deploy:
#    runs-on: ubuntu-latest
#    needs: blogdown
#    steps:
#      - name: Checkout
#        uses: actions/checkout@master
#      - name: Download artifact
#        uses: actions/download-artifact@v1.0.0
#        with:
#          # Artifact name
#          name: _site # optional
#          # Destination path
#          path: _site # optional
#      - name: Deploy to GitHub Pages
#        uses: Cecilapp/GitHub-Pages-deploy@master
#        env:
#           EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
#           GH_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
#           BUILD_DIR: _site/                     # "_site/" by default


